import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/views/Navbar/index'
import Wrapper from '@/components/shared/Wrapper/index'
import Footer from '@/components/views/Footer/index'
import TopLabel from '@/components/views/TopLabel/index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hackathon Two',
  description: 'Generated by Wajid Ali',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopLabel />
        <Wrapper>
          <Navbar />
          <div className='min-h-screen'>
            {children}
          </div>
          <Footer />
        </Wrapper>
      </body>
    </html>
  )
}
